import Navbar from "@/Components/Navbar";
import "./globals.css";
import { DashBoardProvider } from "@/Contexts/DashBoardContext";
import { AuthProvider } from "@/Contexts/AuthContext";
import { ConfigProvider } from "@/Contexts/ConfigContext";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="pt-16">
        <AuthProvider>
          <DashBoardProvider>
            <ConfigProvider>
              <Navbar />
              {children}
            </ConfigProvider>
          </DashBoardProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
